apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}-svc
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
