name: Infrastructure deployment

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      resource_prefix:
        description: 'Prefix for resource name'
        required: true
        default: 'v2-boilerplate'
      environment:
        description: 'Environment name'
        required: true
        default: 'dev'
      deployment_type:
        description: 'Deployment Type (Temporary)'
        required: true
        type: choice
        options:
          - Apply
          - Destroy
        default: Apply

permissions:
  id-token: write
  contents: read

env:
  resource_prefix: ${{ github.event.inputs.resource_prefix }}
  environment: ${{ github.event.inputs.environment }}
  deployment_type: ${{ github.event.inputs.deployment_type }}

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

  deploy:
    name: 'Terragrunt Init/Plan/Apply'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SAGAR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SAGAR }}
          aws-region: us-west-2

      - name: Setup Terraform v1.8.4
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.4
          terraform_wrapper: false

      - name: Setup Terraform version
        run: terraform --version

      - name: Setup Terraform wrapper path
        run: which terraform

      - name: Setup Terragrunt version 0.58.13
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 0.58.13
      
      - name: Get AWS Account ID
        id: aws-account-id
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "ACCOUNT_ID=${ACCOUNT_ID}" >> $GITHUB_ENV
      
      - name: Make preprocess-config.sh executable
        run: chmod +x ./scripts/preprocess-config.sh
      
      - name: Preprocess config.yml for dev
        env:
          RESOURCE_PREFIX: ${{ env.resource_prefix }}
          ENVIRONMENT: ${{ env.environment }}
          ACCOUNT_ID: ${{ env.ACCOUNT_ID }}
        run: |
          export RESOURCE_PREFIX=${{ env.RESOURCE_PREFIX }}
          export ENVIRONMENT=${{ env.ENVIRONMENT }}
          export ACCOUNT_ID=${{ env.ACCOUNT_ID }}
          ./scripts/preprocess-config.sh ./infra/config.yml.template ./infra/environments/${{ env.ENVIRONMENT }}/config.yml

      # - name: cat config.yml
      #   run: cat ./infra/environments/dev/config.yml

      - name: Verify config.yml
        env:
            ENVIRONMENT: ${{ env.environment }}
        run: |
          echo "Contents of config.yml:"
          cat ./infra/environments/${{ env.ENVIRONMENT }}/config.yml
          echo "Location of config.yml:"
          ls -l ./infra/environments/${{ env.ENVIRONMENT }}/config.yml

      - name: Debug CloudFront module directory
        env:
              ENVIRONMENT: ${{ env.environment }}
        run: |
          echo "Contents of CloudFront module directory:"
          ls -R ./infra/environments/${{ env.ENVIRONMENT }}/cloudfront
          echo "Current working directory:"
          pwd
      
      - name: Determine Action
        id: action
        run: |
          if [ "${{ env.deployment_type }}" == "Apply" ]; then
            echo "action=apply" >> $GITHUB_ENV
            echo "::set-output name=action_name::Terragrunt Apply"
          elif [ "${{ env.deployment_type }}" == "Destroy" ]; then
            echo "action=destroy" >> $GITHUB_ENV
            echo "::set-output name=action_name::Terragrunt Destroy"
          else
            echo "Invalid deployment type" && exit 1
        env:
          deployment_type: ${{ env.deployment_type }}
      
      - name: Empty S3 Bucket (if Destroy)
        if: env.action == 'destroy'
        run: |
          aws s3api delete-objects --bucket ${env.resource_prefix}-s3-${env.environment} --delete "$(aws s3api list-object-versions --bucket ${env.resource_prefix}-s3-${env.environment} --query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}')"
          aws s3 rm s3://${env.resource_prefix}-s3-${env.environment} --recursive
          aws s3api wait bucket-not-exists --bucket ${env.resource_prefix}-s3-${env.environment}
      
      - name: Empty ECR Repository (if Destroy)
        if: env.action == 'destroy'
        run: |
          REPO_NAME="${{ env.resource_prefix }}-ecr-${{ env.environment }}"
          IMAGE_TAGS=$(aws ecr list-images --repository-name $REPO_NAME --query 'imageIds[*]' --output json)
          if [ "$IMAGE_TAGS" != "[]" ]; then
            aws ecr batch-delete-image --repository-name $REPO_NAME --image-ids "$IMAGE_TAGS"
          else
            echo "No images to delete in repository $REPO_NAME"
          fi
      
      - name: Destroy Load Balancer (if Destroy)
        if: env.action == 'destroy'
        run: |
          LB_ARN=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(Tags[?Key=='elbv2.k8s.aws/cluster' && Value=='${{ env.resource_prefix }}-cluster-${{ env.environment }}'].Value, '${{ env.resource_prefix }}-cluster-${{ env.environment }}')].LoadBalancerArn" --output text)
          if [ -n "$LB_ARN" ]; then
            aws elbv2 delete-load-balancer --load-balancer-arn $LB_ARN
          else
            echo "No Load Balancer found with the tag elbv2.k8s.aws/cluster:${{ env.resource_prefix }}-cluster-${{ env.environment }}"
          fi

      - name: ${{ steps.action.outputs.action_name }}
        env:
          RESOURCE_PREFIX: ${{ env.resource_prefix }}
          ENVIRONMENT: ${{ env.environment }}
          ACCOUNT_ID: ${{ env.ACCOUNT_ID }}
        run: |
          echo $RESOURCE_PREFIX
          echo $ENVIRONMENT
          echo $ACCOUNT_ID
          cd ./infra/environments/${{ env.environment }}
          if [ "${{ env.action }}" == "apply" ]; then
            terragrunt run-all apply --terragrunt-non-interactive
          elif [ "${{ env.action }}" == "destroy" ]; then
            terragrunt run-all destroy --terragrunt-non-interactive
          fi

      # - name: Terragrunt Apply
      #   env:
      #     RESOURCE_PREFIX: ${{ env.resource_prefix }}
      #     ENVIRONMENT: ${{ env.environment }}
      #     ACCOUNT_ID: ${{ env.ACCOUNT_ID }}
      #   run: |
      #     echo $RESOURCE_PREFIX
      #     echo $ENVIRONMENT
      #     echo $ACCOUNT_ID
      #     cd ./infra/environments/${{ env.environment }}
      #     terragrunt run-all apply --terragrunt-non-interactive
      
      # # **********Debug Steps***********Uncomment when required*********
      # - name: List files in environments directory
      #   run: ls -R ./infra/environments
