name: Infrastructure deployment

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      resource_prefix:
        description: 'Prefix for resource name'
        required: true
        default: 'v2-boilerplate'
      environment:
        description: 'Environment name'
        required: true
        default: 'dev'

permissions:
  id-token: write
  contents: read

env:
  resource_prefix: ${{ github.event.inputs.resource_prefix }}
  environment: ${{ github.event.inputs.environment }}

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

  deploy:
    name: 'Terragrunt Init/Plan/Apply'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SAGAR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SAGAR }}
          aws-region: us-west-2

      - name: Setup Terraform v1.8.4
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.4
          terraform_wrapper: false

      - name: Setup Terraform version
        run: terraform --version

      - name: Setup Terraform wrapper path
        run: which terraform

      - name: Setup Terragrunt version 0.58.13
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 0.58.13
      
      - name: Get AWS Account ID
        id: aws-account-id
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "ACCOUNT_ID=${ACCOUNT_ID}" >> $GITHUB_ENV
      
      - name: Make preprocess-config.sh executable
        run: chmod +x ./scripts/preprocess-config.sh
      
      - name: Preprocess config.yml for dev
        env:
          RESOURCE_PREFIX: ${{ env.resource_prefix }}
          ENVIRONMENT: ${{ env.environment }}
          ACCOUNT_ID: ${{ env.ACCOUNT_ID }}
        run: |
          export RESOURCE_PREFIX=${{ env.RESOURCE_PREFIX }}
          export ENVIRONMENT=${{ env.ENVIRONMENT }}
          export ACCOUNT_ID=${{ env.ACCOUNT_ID }}
          ./scripts/preprocess-config.sh ./infra/config.yml.template ./infra/environments/${{ env.ENVIRONMENT }}/config.yml

      # - name: cat config.yml
      #   run: cat ./infra/environments/dev/config.yml

      - name: Verify config.yml
        env:
            ENVIRONMENT: ${{ env.environment }}
        run: |
          echo "Contents of config.yml:"
          cat ./infra/environments/${{ env.ENVIRONMENT }}/config.yml
          echo "Location of config.yml:"
          ls -l ./infra/environments/${{ env.ENVIRONMENT }}/config.yml

      - name: Debug CloudFront module directory
        env:
              ENVIRONMENT: ${{ env.environment }}
        run: |
          echo "Contents of CloudFront module directory:"
          ls -R ./infra/environments/${{ env.ENVIRONMENT }}/cloudfront
          echo "Current working directory:"
          pwd

      - name: Terragrunt Apply
        env:
          RESOURCE_PREFIX: ${{ env.resource_prefix }}
          ENVIRONMENT: ${{ env.environment }}
          ACCOUNT_ID: ${{ env.ACCOUNT_ID }}
        run: |
          echo $RESOURCE_PREFIX
          echo $ENVIRONMENT
          echo $ACCOUNT_ID
          cd ./infra/environments/${{ env.environment }}
          terragrunt run-all plan --terragrunt-non-interactive
      
      # **********Debug Steps***********Uncomment when required*********
      - name: List files in environments directory
        run: ls -R ./infra/environments